name: Azure App Service CI
on:
  push:
    branches:
      - main
      - azure
    paths-ignore:
      - README.md

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with:
          app-name: bkkchangelog
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
