on:
  workflow_dispatch:
  # schedule:
  #   - cron: '59 18 * * *'
name: Backup
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm install
      - run: cd etl && pnpm run backup
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - run: tar -cvzf etl/.data/backup.ndjson.tar.gz etl/.data/backup.ndjson
      - uses: actions/upload-artifact@v3
        with:
          name: backup
          path: etl/.data/backup.ndjson.tar.gz
          retention-days: 7
