on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,10,18 * * *'
name: ETL
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: pnpm
      - run: pnpm install
      - run: cd etl && pnpm run fetch
      - run: cd etl && pnpm run collect
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - run: cd etl && pnpm run index-changelog
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: data
          path: etl/.data/fetched
          retention-days: 16
